/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import panelView.*;
import java.awt.Color;
import javax.swing.JComponent;

/**
 *
 * @author vina qhurotu aini
 */
public class mainViewForm extends javax.swing.JFrame {
    private int selectedIndex = -1;
    
    private void setForm(JComponent com){
        contentPanel.removeAll();
        contentPanel.add(com);
        contentPanel.repaint();
        contentPanel.revalidate();
    }
    
    private void recolerDefaultSwitchPanel(){
        repaint();
        apotekerPanel.setBackground(new Color(0,0,0,0));
        pelangganPanel.setBackground(new Color(0,0,0,0));
        supplierPanel.setBackground(new Color(0,0,0,0));
        obatPanel.setBackground(new Color(0,0,0,0));
        pengadaanObatPanel.setBackground(new Color(0,0,0,0));
        transaksiPanel.setBackground(new Color(0,0,0,0));
    }

    /**
     * Creates new form mainViewForm
     */
    public mainViewForm() {
        initComponents();
        recolerDefaultSwitchPanel();
        setForm(new WelcomePage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelMenu = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        menulLabel = new javax.swing.JLabel();
        obatPanel = new javax.swing.JPanel();
        obatLabel = new javax.swing.JLabel();
        pengadaanObatPanel = new javax.swing.JPanel();
        pengadaanObatLabel = new javax.swing.JLabel();
        transaksiPanel = new javax.swing.JPanel();
        tansaksiLabel = new javax.swing.JLabel();
        supplierPanel = new javax.swing.JPanel();
        supplierLabel = new javax.swing.JLabel();
        pelangganPanel = new javax.swing.JPanel();
        pelanggalLabel = new javax.swing.JLabel();
        apotekerPanel = new javax.swing.JPanel();
        apotekerLabel = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(116, 5, 13));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconMedical.png"))); // NOI18N
        jLabel1.setText("Atma Medica");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        PanelMenu.setBackground(new java.awt.Color(255, 255, 255));
        PanelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelMenuMouseClicked(evt);
            }
        });

        menuPanel.setBackground(new java.awt.Color(255, 255, 255));
        menuPanel.setFont(new java.awt.Font("Javanese Text", 0, 18)); // NOI18N

        menulLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menulLabel.setForeground(new java.awt.Color(0, 0, 0));
        menulLabel.setText("MENU");

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menulLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        obatPanel.setBackground(new java.awt.Color(255, 255, 255));
        obatPanel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        obatPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                obatPanelMouseClicked(evt);
            }
        });

        obatLabel.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        obatLabel.setForeground(new java.awt.Color(0, 0, 0));
        obatLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        obatLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/obatIcon.png"))); // NOI18N
        obatLabel.setText("Obat");
        obatLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                obatLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout obatPanelLayout = new javax.swing.GroupLayout(obatPanel);
        obatPanel.setLayout(obatPanelLayout);
        obatPanelLayout.setHorizontalGroup(
            obatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(obatPanelLayout.createSequentialGroup()
                .addComponent(obatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        obatPanelLayout.setVerticalGroup(
            obatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(obatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(obatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        pengadaanObatPanel.setBackground(new java.awt.Color(255, 255, 255));
        pengadaanObatPanel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        pengadaanObatPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pengadaanObatPanelMouseClicked(evt);
            }
        });

        pengadaanObatLabel.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        pengadaanObatLabel.setForeground(new java.awt.Color(0, 0, 0));
        pengadaanObatLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pengadaanObatLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/supplyIcon.png"))); // NOI18N
        pengadaanObatLabel.setText("Pengadaan Obat");
        pengadaanObatLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pengadaanObatLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pengadaanObatPanelLayout = new javax.swing.GroupLayout(pengadaanObatPanel);
        pengadaanObatPanel.setLayout(pengadaanObatPanelLayout);
        pengadaanObatPanelLayout.setHorizontalGroup(
            pengadaanObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pengadaanObatPanelLayout.createSequentialGroup()
                .addComponent(pengadaanObatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        pengadaanObatPanelLayout.setVerticalGroup(
            pengadaanObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pengadaanObatPanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(pengadaanObatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        transaksiPanel.setBackground(new java.awt.Color(255, 255, 255));
        transaksiPanel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        transaksiPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiPanelMouseClicked(evt);
            }
        });

        tansaksiLabel.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        tansaksiLabel.setForeground(new java.awt.Color(0, 0, 0));
        tansaksiLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tansaksiLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/transaksiIcon.png"))); // NOI18N
        tansaksiLabel.setText("Transaksi");
        tansaksiLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tansaksiLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout transaksiPanelLayout = new javax.swing.GroupLayout(transaksiPanel);
        transaksiPanel.setLayout(transaksiPanelLayout);
        transaksiPanelLayout.setHorizontalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tansaksiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        transaksiPanelLayout.setVerticalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tansaksiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        supplierPanel.setBackground(new java.awt.Color(255, 255, 255));
        supplierPanel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        supplierPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierPanelMouseClicked(evt);
            }
        });

        supplierLabel.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        supplierLabel.setForeground(new java.awt.Color(0, 0, 0));
        supplierLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        supplierLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/transitIcon.png"))); // NOI18N
        supplierLabel.setText("Supplier");
        supplierLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout supplierPanelLayout = new javax.swing.GroupLayout(supplierPanel);
        supplierPanel.setLayout(supplierPanelLayout);
        supplierPanelLayout.setHorizontalGroup(
            supplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierPanelLayout.createSequentialGroup()
                .addComponent(supplierLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        supplierPanelLayout.setVerticalGroup(
            supplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(supplierLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        pelangganPanel.setBackground(new java.awt.Color(255, 255, 255));
        pelangganPanel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        pelangganPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pelangganPanelMouseClicked(evt);
            }
        });

        pelanggalLabel.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        pelanggalLabel.setForeground(new java.awt.Color(0, 0, 0));
        pelanggalLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pelanggalLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pelangganIcon.png"))); // NOI18N
        pelanggalLabel.setText("Pelanggan");
        pelanggalLabel.setMaximumSize(new java.awt.Dimension(85, 24));
        pelanggalLabel.setMinimumSize(new java.awt.Dimension(85, 24));
        pelanggalLabel.setPreferredSize(new java.awt.Dimension(85, 24));
        pelanggalLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pelanggalLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pelangganPanelLayout = new javax.swing.GroupLayout(pelangganPanel);
        pelangganPanel.setLayout(pelangganPanelLayout);
        pelangganPanelLayout.setHorizontalGroup(
            pelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pelangganPanelLayout.createSequentialGroup()
                .addComponent(pelanggalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pelangganPanelLayout.setVerticalGroup(
            pelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pelanggalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        apotekerPanel.setBackground(new java.awt.Color(255, 255, 255));
        apotekerPanel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        apotekerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apotekerPanelMouseClicked(evt);
            }
        });

        apotekerLabel.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        apotekerLabel.setForeground(new java.awt.Color(0, 0, 0));
        apotekerLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        apotekerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/apotekerIcon.png"))); // NOI18N
        apotekerLabel.setText("Apoteker");
        apotekerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apotekerLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout apotekerPanelLayout = new javax.swing.GroupLayout(apotekerPanel);
        apotekerPanel.setLayout(apotekerPanelLayout);
        apotekerPanelLayout.setHorizontalGroup(
            apotekerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apotekerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(apotekerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        apotekerPanelLayout.setVerticalGroup(
            apotekerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apotekerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(apotekerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(obatPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(supplierPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pelangganPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(menuPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(apotekerPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pengadaanObatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transaksiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apotekerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pelangganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supplierPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(obatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pengadaanObatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transaksiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        contentPanel.setForeground(new java.awt.Color(0, 0, 0));
        contentPanel.setOpaque(false);
        contentPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apotekerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apotekerLabelMouseClicked
       // TODO add your handling code here:
        if (selectedIndex == 1)
            return;
       
        recolerDefaultSwitchPanel();
        apotekerPanel.setBackground(new Color(116,5,13));
        setForm(new ApotekerPanel());
        selectedIndex = 1;
    }//GEN-LAST:event_apotekerLabelMouseClicked

    private void PanelMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelMenuMouseClicked

    private void pelanggalLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pelanggalLabelMouseClicked
        // TODO add your handling code here:
        if (selectedIndex == 2)
            return;

        recolerDefaultSwitchPanel();
        pelangganPanel.setBackground(new Color(116,5,13));
        setForm(new PelangganPanel());
        selectedIndex = 2;
    }//GEN-LAST:event_pelanggalLabelMouseClicked

    private void supplierLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierLabelMouseClicked
        // TODO add your handling code here:
        if (selectedIndex == 3)
            return;

        recolerDefaultSwitchPanel();
        supplierPanel.setBackground(new Color(116,5,13));
        setForm(new SupplierPanel());
        selectedIndex = 3;
    }//GEN-LAST:event_supplierLabelMouseClicked

    private void pelangganPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pelangganPanelMouseClicked
        // TODO add your handling code here:
        if (selectedIndex == 2)
            return;

        recolerDefaultSwitchPanel();
        pelangganPanel.setBackground(new Color(116,5,13));
        setForm(new PelangganPanel());
        selectedIndex = 2;
    }//GEN-LAST:event_pelangganPanelMouseClicked

    private void obatLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_obatLabelMouseClicked
        // TODO add your handling code here:
        if (selectedIndex == 4)
            return;

        recolerDefaultSwitchPanel();
        obatPanel.setBackground(new Color(116,5,13));
        setForm(new ObatPanel());
        selectedIndex = 4;
    }//GEN-LAST:event_obatLabelMouseClicked

    private void pengadaanObatLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengadaanObatLabelMouseClicked
        // TODO add your handling code here:
        if (selectedIndex == 5)
            return;

        recolerDefaultSwitchPanel();
        pengadaanObatPanel.setBackground(new Color(116,5,13));
        setForm(new PengadaanObatPanel());
        selectedIndex = 5;
    }//GEN-LAST:event_pengadaanObatLabelMouseClicked

    private void tansaksiLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tansaksiLabelMouseClicked
        // TODO add your handling code here:
        if (selectedIndex == 6)
            return;

        recolerDefaultSwitchPanel();
        transaksiPanel.setBackground(new Color(116,5,13));
        setForm(new TransaksiPanel());
        selectedIndex = 6;
    }//GEN-LAST:event_tansaksiLabelMouseClicked

    private void apotekerPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apotekerPanelMouseClicked
        // TODO add your handling code here:
        if (selectedIndex == 1)
            return;
       
        recolerDefaultSwitchPanel();
        apotekerPanel.setBackground(new Color(116,5,13));
        setForm(new ApotekerPanel());
        selectedIndex = 1;
    }//GEN-LAST:event_apotekerPanelMouseClicked

    private void supplierPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierPanelMouseClicked
        // TODO add your handling code here:
        if (selectedIndex == 3)
            return;

        recolerDefaultSwitchPanel();
        supplierPanel.setBackground(new Color(116,5,13));
        setForm(new SupplierPanel());
        selectedIndex = 3;
    }//GEN-LAST:event_supplierPanelMouseClicked

    private void obatPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_obatPanelMouseClicked
        // TODO add your handling code here:
        if (selectedIndex == 4)
            return;

        recolerDefaultSwitchPanel();
        obatPanel.setBackground(new Color(116,5,13));
        setForm(new ObatPanel());
        selectedIndex = 4;
    }//GEN-LAST:event_obatPanelMouseClicked

    private void pengadaanObatPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengadaanObatPanelMouseClicked
        // TODO add your handling code here:
        if (selectedIndex == 5)
            return;

        recolerDefaultSwitchPanel();
        pengadaanObatPanel.setBackground(new Color(116,5,13));
        setForm(new PengadaanObatPanel());
        selectedIndex = 5;
    }//GEN-LAST:event_pengadaanObatPanelMouseClicked

    private void transaksiPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiPanelMouseClicked
        // TODO add your handling code here:
        if (selectedIndex == 6)
            return;

        recolerDefaultSwitchPanel();
        transaksiPanel.setBackground(new Color(116,5,13));
        setForm(new TransaksiPanel());
        selectedIndex = 6;
    }//GEN-LAST:event_transaksiPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainViewForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JLabel apotekerLabel;
    private javax.swing.JPanel apotekerPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel menulLabel;
    private javax.swing.JLabel obatLabel;
    private javax.swing.JPanel obatPanel;
    private javax.swing.JLabel pelanggalLabel;
    private javax.swing.JPanel pelangganPanel;
    private javax.swing.JLabel pengadaanObatLabel;
    private javax.swing.JPanel pengadaanObatPanel;
    private javax.swing.JLabel supplierLabel;
    private javax.swing.JPanel supplierPanel;
    private javax.swing.JLabel tansaksiLabel;
    private javax.swing.JPanel transaksiPanel;
    // End of variables declaration//GEN-END:variables
}
