/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelView;

import control.ObatControl;
import exception.InputKosongException;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import java.awt.Component;

import model.Obat;

import table.TableObat;

/**
 *
 * @author vina qhurotu aini
 */
public class ObatPanel extends javax.swing.JPanel {

    private ObatControl obatControl;
    private Obat obat = null;
    String action = null;
    int selectedId = 0;
    
    List<Obat> listObat;
    
    private Component rootPane;
    
    private void inputKosongException() throws InputKosongException{
        if(namaObatField.getText().isEmpty() 
                || hargaObatField.getText().isEmpty() || jumlahObatField.getText().isEmpty() 
                || kategoriGroup.getSelection().getActionCommand() == null)
            throw new InputKosongException();
    }
    
    //RADIO BUTTON
    public void setRadioButtonValue(){
        obatBebasButton.setActionCommand("Obat Bebas");
        obatBebasTerbatasButton.setActionCommand("Obat Bebas Terbatas");
        obatKerasButton.setActionCommand("Obat Keras");
        obatPsikotropikaButton.setActionCommand("Obat Psikotropika");
        obatNarkotikaButton.setActionCommand("Obat Narkotika");
    }
    
    //TABLE SHOW
    public void showTableBySearch(String target){
        tableData.setModel(obatControl.showTable(target));
    }
    
    //Obat Set Komponen
    public void setComponent(boolean value){
        idObatField.setEnabled(value);
        namaObatField.setEnabled(value);
        jumlahObatField.setEnabled(value);
        hargaObatField.setEnabled(value);
        
        saveButton.setEnabled(value);
        cancelButton.setEnabled(value);
    }
    
    public void setRadioComponent(boolean value){
        obatBebasButton.setEnabled(value);
        obatBebasTerbatasButton.setEnabled(value);
        obatKerasButton.setEnabled(value);
        obatNarkotikaButton.setEnabled(value);
        obatPsikotropikaButton.setEnabled(value);
    }
    
    //Obat Set Edit Delete Button
    public void setEditDeleteButton(boolean value){
        barukanButton.setEnabled(value);
        hapusButton.setEnabled(value);
    }
    
    public void clearText(){
        idObatField.setText("");
        namaObatField.setText("");
        hargaObatField.setText("");
        jumlahObatField.setText("");
        kategoriGroup.clearSelection();
        searchInput.setText("");
    }
    
    public ObatPanel() {
        initComponents();
        
        obatControl = new ObatControl();
        
        setRadioButtonValue();
        showTableBySearch("");
        
        //RESET
        clearText();
        setComponent(false);
        setRadioComponent(false);
        setEditDeleteButton(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kategoriGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        ApotekLabel = new javax.swing.JLabel();
        KaryawanApotekLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        searchInputPanel = new javax.swing.JPanel();
        searchInput = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        buttonPanel = new javax.swing.JPanel();
        barukanButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        tambahDataButton = new javax.swing.JButton();
        dataFormPanel = new javax.swing.JPanel();
        jumlahObatPanel = new javax.swing.JPanel();
        jumlahObatLabel = new javax.swing.JLabel();
        jumlahObatField = new javax.swing.JTextField();
        hargaObatPanel = new javax.swing.JPanel();
        hargaObatLabel = new javax.swing.JLabel();
        hargaObatField = new javax.swing.JTextField();
        idObatPanel = new javax.swing.JPanel();
        idObatLabel = new javax.swing.JLabel();
        idObatField = new javax.swing.JTextField();
        namaObatPanel = new javax.swing.JPanel();
        namaObatLabel = new javax.swing.JLabel();
        namaObatField = new javax.swing.JTextField();
        kategoriPanel = new javax.swing.JPanel();
        kategoriLabel = new javax.swing.JLabel();
        obatBebasButton = new javax.swing.JRadioButton();
        obatBebasTerbatasButton = new javax.swing.JRadioButton();
        obatKerasButton = new javax.swing.JRadioButton();
        obatPsikotropikaButton = new javax.swing.JRadioButton();
        obatNarkotikaButton = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(1240, 704));

        jPanel1.setBackground(new java.awt.Color(218, 168, 168));
        jPanel1.setPreferredSize(new java.awt.Dimension(1210, 706));

        ApotekLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        ApotekLabel.setForeground(new java.awt.Color(0, 0, 0));
        ApotekLabel.setText("Obat");

        KaryawanApotekLabel.setFont(new java.awt.Font("Bahnschrift", 0, 10)); // NOI18N
        KaryawanApotekLabel.setForeground(new java.awt.Color(109, 96, 96));
        KaryawanApotekLabel.setText("Barang yang dijual");

        mainPanel.setBackground(new java.awt.Color(238, 230, 230));

        searchInputPanel.setBackground(new java.awt.Color(238, 230, 230));

        searchInput.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchInputKeyPressed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(27, 26, 85));
        searchButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Cari");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchInputPanelLayout = new javax.swing.GroupLayout(searchInputPanel);
        searchInputPanel.setLayout(searchInputPanelLayout);
        searchInputPanelLayout.setHorizontalGroup(
            searchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchInputPanelLayout.createSequentialGroup()
                .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchInputPanelLayout.setVerticalGroup(
            searchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchInput)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cancelButton.setBackground(new java.awt.Color(237, 8, 0));
        cancelButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Batalkan");
        cancelButton.setPreferredSize(new java.awt.Dimension(72, 21));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(51, 178, 73));
        saveButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Simpan");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableData);

        buttonPanel.setBackground(new java.awt.Color(238, 230, 230));

        barukanButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanButton.setText("Barukan");
        barukanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanButtonActionPerformed(evt);
            }
        });

        hapusButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        tambahDataButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahDataButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahDataButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahDataButton.setText("Tambah");
        tambahDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahDataButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahDataButton)
                .addGap(18, 18, 18)
                .addComponent(barukanButton)
                .addGap(18, 18, 18)
                .addComponent(hapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(tambahDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dataFormPanel.setBackground(new java.awt.Color(238, 230, 230));

        jumlahObatPanel.setBackground(new java.awt.Color(238, 230, 230));

        jumlahObatLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jumlahObatLabel.setForeground(new java.awt.Color(0, 0, 0));
        jumlahObatLabel.setText("Jangka Simpan Obat (bulan)");

        jumlahObatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahObatFieldActionPerformed(evt);
            }
        });
        jumlahObatField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jumlahObatFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jumlahObatPanelLayout = new javax.swing.GroupLayout(jumlahObatPanel);
        jumlahObatPanel.setLayout(jumlahObatPanelLayout);
        jumlahObatPanelLayout.setHorizontalGroup(
            jumlahObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jumlahObatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jumlahObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jumlahObatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumlahObatField))
                .addContainerGap())
        );
        jumlahObatPanelLayout.setVerticalGroup(
            jumlahObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jumlahObatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jumlahObatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jumlahObatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hargaObatPanel.setBackground(new java.awt.Color(238, 230, 230));

        hargaObatLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        hargaObatLabel.setForeground(new java.awt.Color(0, 0, 0));
        hargaObatLabel.setText("Harga Obat");

        hargaObatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaObatFieldActionPerformed(evt);
            }
        });
        hargaObatField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hargaObatFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout hargaObatPanelLayout = new javax.swing.GroupLayout(hargaObatPanel);
        hargaObatPanel.setLayout(hargaObatPanelLayout);
        hargaObatPanelLayout.setHorizontalGroup(
            hargaObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hargaObatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hargaObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hargaObatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(hargaObatPanelLayout.createSequentialGroup()
                        .addComponent(hargaObatField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        hargaObatPanelLayout.setVerticalGroup(
            hargaObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hargaObatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hargaObatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaObatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        idObatPanel.setBackground(new java.awt.Color(238, 230, 230));

        idObatLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        idObatLabel.setForeground(new java.awt.Color(0, 0, 0));
        idObatLabel.setText("ID Obat");

        idObatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idObatFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout idObatPanelLayout = new javax.swing.GroupLayout(idObatPanel);
        idObatPanel.setLayout(idObatPanelLayout);
        idObatPanelLayout.setHorizontalGroup(
            idObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idObatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idObatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idObatField, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                .addContainerGap())
        );
        idObatPanelLayout.setVerticalGroup(
            idObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idObatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idObatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idObatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        namaObatPanel.setBackground(new java.awt.Color(238, 230, 230));

        namaObatLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        namaObatLabel.setForeground(new java.awt.Color(0, 0, 0));
        namaObatLabel.setText("Nama Obat");

        javax.swing.GroupLayout namaObatPanelLayout = new javax.swing.GroupLayout(namaObatPanel);
        namaObatPanel.setLayout(namaObatPanelLayout);
        namaObatPanelLayout.setHorizontalGroup(
            namaObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaObatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaObatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaObatField))
                .addContainerGap())
        );
        namaObatPanelLayout.setVerticalGroup(
            namaObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaObatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaObatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaObatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        kategoriPanel.setBackground(new java.awt.Color(238, 230, 230));

        kategoriLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        kategoriLabel.setForeground(new java.awt.Color(0, 0, 0));
        kategoriLabel.setText("Kategori");

        kategoriGroup.add(obatBebasButton);
        obatBebasButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        obatBebasButton.setForeground(new java.awt.Color(0, 0, 0));
        obatBebasButton.setText("Obat Bebas");
        obatBebasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obatBebasButtonActionPerformed(evt);
            }
        });

        kategoriGroup.add(obatBebasTerbatasButton);
        obatBebasTerbatasButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        obatBebasTerbatasButton.setForeground(new java.awt.Color(0, 0, 0));
        obatBebasTerbatasButton.setText("Obat Bebas Terbatas");
        obatBebasTerbatasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obatBebasTerbatasButtonActionPerformed(evt);
            }
        });

        kategoriGroup.add(obatKerasButton);
        obatKerasButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        obatKerasButton.setForeground(new java.awt.Color(0, 0, 0));
        obatKerasButton.setText("Obat Keras");
        obatKerasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obatKerasButtonActionPerformed(evt);
            }
        });

        kategoriGroup.add(obatPsikotropikaButton);
        obatPsikotropikaButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        obatPsikotropikaButton.setForeground(new java.awt.Color(0, 0, 0));
        obatPsikotropikaButton.setText("Obat Psikotropika");
        obatPsikotropikaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obatPsikotropikaButtonActionPerformed(evt);
            }
        });

        kategoriGroup.add(obatNarkotikaButton);
        obatNarkotikaButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        obatNarkotikaButton.setForeground(new java.awt.Color(0, 0, 0));
        obatNarkotikaButton.setText("Obat Narkotika");
        obatNarkotikaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obatNarkotikaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kategoriPanelLayout = new javax.swing.GroupLayout(kategoriPanel);
        kategoriPanel.setLayout(kategoriPanelLayout);
        kategoriPanelLayout.setHorizontalGroup(
            kategoriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kategoriPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kategoriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kategoriLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(kategoriPanelLayout.createSequentialGroup()
                        .addGroup(kategoriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(obatBebasButton)
                            .addComponent(obatBebasTerbatasButton)
                            .addComponent(obatKerasButton)
                            .addComponent(obatPsikotropikaButton)
                            .addComponent(obatNarkotikaButton))
                        .addGap(0, 147, Short.MAX_VALUE)))
                .addContainerGap())
        );
        kategoriPanelLayout.setVerticalGroup(
            kategoriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kategoriPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kategoriLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(obatBebasButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(obatBebasTerbatasButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(obatKerasButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(obatPsikotropikaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(obatNarkotikaButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dataFormPanelLayout = new javax.swing.GroupLayout(dataFormPanel);
        dataFormPanel.setLayout(dataFormPanelLayout);
        dataFormPanelLayout.setHorizontalGroup(
            dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idObatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaObatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hargaObatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahObatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(kategoriPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        dataFormPanelLayout.setVerticalGroup(
            dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataFormPanelLayout.createSequentialGroup()
                        .addGroup(dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idObatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hargaObatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dataFormPanelLayout.createSequentialGroup()
                                .addComponent(jumlahObatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(namaObatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(kategoriPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(searchInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(ApotekLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KaryawanApotekLabel)
                .addContainerGap(1093, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(41, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApotekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KaryawanApotekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(674, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(18, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1240, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataMouseClicked
        action = "baharui";
        
        tambahDataButton.setEnabled(false);
        cancelButton.setEnabled(true);
        saveButton.setEnabled(true);
        setEditDeleteButton(true);
        
        setComponent(false);
        setRadioComponent(false);
        kategoriGroup.clearSelection();
        
        int clickedRow = tableData.getSelectedRow();
        TableModel tableModel = tableData.getModel();
        
        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 0).toString());
        
        idObatField.setText(tableModel.getValueAt(clickedRow, 0).toString());
        namaObatField.setText(tableModel.getValueAt(clickedRow, 1).toString());
        hargaObatField.setText(tableModel.getValueAt(clickedRow, 3).toString());
        jumlahObatField.setText(tableModel.getValueAt(clickedRow, 4).toString());
        
        String kategoriObat = tableModel.getValueAt(clickedRow, 2).toString();
        
        switch(kategoriObat){
            case "Obat Bebas":
                obatBebasButton.setSelected(true);
                break;
            case "Obat Bebas Terbatas":
                obatBebasTerbatasButton.setSelected(true);
                break;
            case "Obat Keras":
                obatKerasButton.setSelected(true);
                break;
            case "Obat Psikotropika":
                obatPsikotropikaButton.setSelected(true);
                break;
            case "Obat Narkotika":
                obatPsikotropikaButton.setSelected(true);
        }
        
        cancelButton.setEnabled(true);
    }//GEN-LAST:event_tableDataMouseClicked

    private void searchInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchInputKeyPressed

    }//GEN-LAST:event_searchInputKeyPressed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        showTableBySearch(searchInput.getText());
        
        clearText();
        setComponent(false);
        setEditDeleteButton(false);
        setRadioComponent(false);
        kategoriGroup.clearSelection();
        tambahDataButton.setEnabled(true);
        
    }//GEN-LAST:event_searchButtonActionPerformed

    private void barukanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanButtonActionPerformed
        action = "baharui";
        setComponent(true);
        idObatField.setEnabled(false);
        setEditDeleteButton(true);
        setRadioComponent(true);
    }//GEN-LAST:event_barukanButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        action = "hapus";
        
        int opsi = JOptionPane.showConfirmDialog(rootPane, "Yakin Ingin Hapus ?", "Hapus Data", JOptionPane.YES_NO_CANCEL_OPTION);
        if(opsi == JOptionPane.NO_OPTION || opsi == JOptionPane.CANCEL_OPTION || opsi == JOptionPane.CLOSED_OPTION){
            return;
        }
        
        obatControl.deleteObat(selectedId);
        
        clearText();
        setComponent(false);
        setEditDeleteButton(false);
        setRadioComponent(false);
        kategoriGroup.clearSelection();
        tambahDataButton.setEnabled(true);
        showTableBySearch("");
        
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void tambahDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahDataButtonActionPerformed
        action = "tambah";
        clearText();
        setComponent(true);
        idObatField.setEnabled(false);
        setRadioComponent(true);
    }//GEN-LAST:event_tambahDataButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        
        String kategoriObat = "";
        
        try{
            inputKosongException();
            
            double harga = Double.parseDouble(hargaObatField.getText());
            int jumlah = Integer.parseInt(jumlahObatField.getText());
            
            kategoriObat = kategoriGroup.getSelection().getActionCommand();
            
            int opsi = JOptionPane.showConfirmDialog(rootPane, "Yakin Ingin melakukan " +action+ "?");
            if(opsi == JOptionPane.NO_OPTION || opsi == JOptionPane.CANCEL_OPTION || opsi == JOptionPane.CLOSED_OPTION){
                return;
            }
            
            if(action.equals("tambah")){
                Obat obat = new Obat(namaObatField.getText(), kategoriObat, Double.parseDouble(hargaObatField.getText()), Integer.parseInt(jumlahObatField.getText()));
                obatControl.insertDataObat(obat);
            }else{
                Obat obat = new Obat(namaObatField.getText(), kategoriObat, Double.parseDouble(hargaObatField.getText()), Integer.parseInt(jumlahObatField.getText()));
                obatControl.updateObat(obat, Integer.parseInt(idObatField.getText()));
                selectedId = -1;
            }
            
            clearText();
            setComponent(false);
            setEditDeleteButton(false);
            setRadioComponent(false);
            kategoriGroup.clearSelection();
            tambahDataButton.setEnabled(true);
            showTableBySearch("");
        }catch(InputKosongException e){
            JOptionPane.showMessageDialog(rootPane, e.message());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "Harga dan Jumlah Obat Harus Angka");
        }
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        clearText();
        setEditDeleteButton(false);
        setComponent(false);
        setEditDeleteButton(false);
        setRadioComponent(false);
        
        tambahDataButton.setEnabled(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void jumlahObatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahObatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahObatFieldActionPerformed

    private void hargaObatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaObatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaObatFieldActionPerformed

    private void idObatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idObatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idObatFieldActionPerformed

    private void obatBebasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obatBebasButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obatBebasButtonActionPerformed

    private void obatBebasTerbatasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obatBebasTerbatasButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obatBebasTerbatasButtonActionPerformed

    private void obatKerasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obatKerasButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obatKerasButtonActionPerformed

    private void obatPsikotropikaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obatPsikotropikaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obatPsikotropikaButtonActionPerformed

    private void obatNarkotikaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obatNarkotikaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obatNarkotikaButtonActionPerformed

    private void hargaObatFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargaObatFieldKeyTyped
        
    }//GEN-LAST:event_hargaObatFieldKeyTyped

    private void jumlahObatFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahObatFieldKeyTyped
        
    }//GEN-LAST:event_jumlahObatFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApotekLabel;
    private javax.swing.JLabel KaryawanApotekLabel;
    private javax.swing.JButton barukanButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel dataFormPanel;
    private javax.swing.JButton hapusButton;
    private javax.swing.JTextField hargaObatField;
    private javax.swing.JLabel hargaObatLabel;
    private javax.swing.JPanel hargaObatPanel;
    private javax.swing.JTextField idObatField;
    private javax.swing.JLabel idObatLabel;
    private javax.swing.JPanel idObatPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlahObatField;
    private javax.swing.JLabel jumlahObatLabel;
    private javax.swing.JPanel jumlahObatPanel;
    private javax.swing.ButtonGroup kategoriGroup;
    private javax.swing.JLabel kategoriLabel;
    private javax.swing.JPanel kategoriPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField namaObatField;
    private javax.swing.JLabel namaObatLabel;
    private javax.swing.JPanel namaObatPanel;
    private javax.swing.JRadioButton obatBebasButton;
    private javax.swing.JRadioButton obatBebasTerbatasButton;
    private javax.swing.JRadioButton obatKerasButton;
    private javax.swing.JRadioButton obatNarkotikaButton;
    private javax.swing.JRadioButton obatPsikotropikaButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchInput;
    private javax.swing.JPanel searchInputPanel;
    private javax.swing.JTable tableData;
    private javax.swing.JButton tambahDataButton;
    // End of variables declaration//GEN-END:variables
}
