/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelView;
import control.PelangganControl;
import exception.InputKosongException;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import java.awt.Component;

import model.Pelanggan;
import table.TablePelanggan;
/**
 *
 * @author vina qhurotu aini
 */
public class PelangganPanel extends javax.swing.JPanel {
    private PelangganControl pc ;
    private Pelanggan p = null;

    String action = null;
    int selectedId = 0;
    List<Pelanggan> listPelanggan;
    private Component rootPane;
    
    public PelangganPanel() {
        pc = new PelangganControl();
        initComponents();
        setOpaque(false);
        
        showTableBySearch("");
        
        setComponentsPelanggan(false);
        setPelangganEditDeleteButton(false);
        clearText();   
    
    }
    
    public void inputKosongPelangganException() throws InputKosongException{
        if(namaPelangganField.getText().isEmpty() || nomorTeleponPelangganField.getText().isEmpty()||alamatPelangganArea.getText().isEmpty())
            throw new InputKosongException();
    }
    
    public boolean isInteger(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
     public void setComponentsPelanggan(boolean value){
        idPelangganField.setEnabled(value);
        namaPelangganField.setEnabled(value);
        nomorTeleponPelangganField.setEnabled(value);
        alamatPelangganArea.setEnabled(value);
        
        saveButton.setEnabled(value);
        cancelButton.setEnabled(value);
    }
    
    public void setPelangganEditDeleteButton(boolean value){
        barukanButton.setEnabled(value);
        hapusButton.setEnabled(value);
    }
    
    public void clearText(){
        idPelangganField.setText("");
        namaPelangganField.setText("");
        nomorTeleponPelangganField.setText("");
        alamatPelangganArea.setText("");
        searchInput.setText("");
    }
    
    public void showTableBySearch(String target){
        tableData.setModel(pc.showTable(target));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ApotekLabel = new javax.swing.JLabel();
        KaryawanApotekLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        searchInputPanel = new javax.swing.JPanel();
        searchInput = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        buttonPanel = new javax.swing.JPanel();
        barukanButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        tambahDataButton = new javax.swing.JButton();
        dataFormPanel = new javax.swing.JPanel();
        idPelangganPanel = new javax.swing.JPanel();
        idPelangganLabel = new javax.swing.JLabel();
        idPelangganField = new javax.swing.JTextField();
        namaPelangganPanel = new javax.swing.JPanel();
        namaPelangganLabel = new javax.swing.JLabel();
        namaPelangganField = new javax.swing.JTextField();
        nomorTeleponPelangganPanel = new javax.swing.JPanel();
        nomorTeleponLabelPelanggan = new javax.swing.JLabel();
        nomorTeleponPelangganField = new javax.swing.JTextField();
        alamatPelangganPanel = new javax.swing.JPanel();
        alamatPelangganLabel = new javax.swing.JLabel();
        alamatPelangganScrollPanel = new javax.swing.JScrollPane();
        alamatPelangganArea = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(1240, 704));

        jPanel1.setBackground(new java.awt.Color(218, 168, 168));
        jPanel1.setPreferredSize(new java.awt.Dimension(1210, 706));

        ApotekLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        ApotekLabel.setForeground(new java.awt.Color(0, 0, 0));
        ApotekLabel.setText("Pelanggan");

        KaryawanApotekLabel.setFont(new java.awt.Font("Bahnschrift", 0, 10)); // NOI18N
        KaryawanApotekLabel.setForeground(new java.awt.Color(109, 96, 96));
        KaryawanApotekLabel.setText("Pembeli Obat");

        mainPanel.setBackground(new java.awt.Color(238, 230, 230));

        searchInputPanel.setBackground(new java.awt.Color(238, 230, 230));

        searchInput.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchInputKeyPressed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(27, 26, 85));
        searchButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Cari");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchInputPanelLayout = new javax.swing.GroupLayout(searchInputPanel);
        searchInputPanel.setLayout(searchInputPanelLayout);
        searchInputPanelLayout.setHorizontalGroup(
            searchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchInputPanelLayout.createSequentialGroup()
                .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchInputPanelLayout.setVerticalGroup(
            searchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchInput)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cancelButton.setBackground(new java.awt.Color(237, 8, 0));
        cancelButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Batalkan");
        cancelButton.setPreferredSize(new java.awt.Dimension(72, 21));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(51, 178, 73));
        saveButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Simpan");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableData);

        buttonPanel.setBackground(new java.awt.Color(238, 230, 230));

        barukanButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanButton.setText("Barukan");
        barukanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanButtonActionPerformed(evt);
            }
        });

        hapusButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        tambahDataButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahDataButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahDataButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahDataButton.setText("Tambah");
        tambahDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahDataButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahDataButton)
                .addGap(18, 18, 18)
                .addComponent(barukanButton)
                .addGap(18, 18, 18)
                .addComponent(hapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(tambahDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dataFormPanel.setBackground(new java.awt.Color(238, 230, 230));

        idPelangganPanel.setBackground(new java.awt.Color(238, 230, 230));

        idPelangganLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        idPelangganLabel.setForeground(new java.awt.Color(0, 0, 0));
        idPelangganLabel.setText("ID Pelanggan");

        idPelangganField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPelangganFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout idPelangganPanelLayout = new javax.swing.GroupLayout(idPelangganPanel);
        idPelangganPanel.setLayout(idPelangganPanelLayout);
        idPelangganPanelLayout.setHorizontalGroup(
            idPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idPelangganLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idPelangganField))
                .addContainerGap())
        );
        idPelangganPanelLayout.setVerticalGroup(
            idPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idPelangganLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idPelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        namaPelangganPanel.setBackground(new java.awt.Color(238, 230, 230));

        namaPelangganLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        namaPelangganLabel.setForeground(new java.awt.Color(0, 0, 0));
        namaPelangganLabel.setText("Nama Pelanggan");

        javax.swing.GroupLayout namaPelangganPanelLayout = new javax.swing.GroupLayout(namaPelangganPanel);
        namaPelangganPanel.setLayout(namaPelangganPanelLayout);
        namaPelangganPanelLayout.setHorizontalGroup(
            namaPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaPelangganLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(namaPelangganField))
                .addContainerGap())
        );
        namaPelangganPanelLayout.setVerticalGroup(
            namaPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaPelangganLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaPelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        nomorTeleponPelangganPanel.setBackground(new java.awt.Color(238, 230, 230));

        nomorTeleponLabelPelanggan.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        nomorTeleponLabelPelanggan.setForeground(new java.awt.Color(0, 0, 0));
        nomorTeleponLabelPelanggan.setText("Nomor Telepon");

        nomorTeleponPelangganField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomorTeleponPelangganFieldActionPerformed(evt);
            }
        });
        nomorTeleponPelangganField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomorTeleponPelangganFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout nomorTeleponPelangganPanelLayout = new javax.swing.GroupLayout(nomorTeleponPelangganPanel);
        nomorTeleponPelangganPanel.setLayout(nomorTeleponPelangganPanelLayout);
        nomorTeleponPelangganPanelLayout.setHorizontalGroup(
            nomorTeleponPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomorTeleponPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nomorTeleponPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomorTeleponLabelPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(nomorTeleponPelangganField))
                .addContainerGap())
        );
        nomorTeleponPelangganPanelLayout.setVerticalGroup(
            nomorTeleponPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomorTeleponPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomorTeleponLabelPelanggan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomorTeleponPelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        alamatPelangganPanel.setBackground(new java.awt.Color(238, 230, 230));

        alamatPelangganLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        alamatPelangganLabel.setForeground(new java.awt.Color(0, 0, 0));
        alamatPelangganLabel.setText("Alamat");

        javax.swing.GroupLayout alamatPelangganPanelLayout = new javax.swing.GroupLayout(alamatPelangganPanel);
        alamatPelangganPanel.setLayout(alamatPelangganPanelLayout);
        alamatPelangganPanelLayout.setHorizontalGroup(
            alamatPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alamatPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alamatPelangganLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        alamatPelangganPanelLayout.setVerticalGroup(
            alamatPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alamatPelangganPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alamatPelangganLabel))
        );

        alamatPelangganArea.setColumns(20);
        alamatPelangganArea.setRows(5);
        alamatPelangganScrollPanel.setViewportView(alamatPelangganArea);

        javax.swing.GroupLayout dataFormPanelLayout = new javax.swing.GroupLayout(dataFormPanel);
        dataFormPanel.setLayout(dataFormPanelLayout);
        dataFormPanelLayout.setHorizontalGroup(
            dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(idPelangganPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(namaPelangganPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(nomorTeleponPelangganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataFormPanelLayout.createSequentialGroup()
                        .addComponent(alamatPelangganPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(828, 828, 828))
                    .addGroup(dataFormPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(alamatPelangganScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        dataFormPanelLayout.setVerticalGroup(
            dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataFormPanelLayout.createSequentialGroup()
                        .addComponent(idPelangganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaPelangganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomorTeleponPelangganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dataFormPanelLayout.createSequentialGroup()
                        .addComponent(alamatPelangganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alamatPelangganScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(searchInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(ApotekLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KaryawanApotekLabel)
                .addContainerGap(1086, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(41, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApotekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KaryawanApotekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(674, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(18, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1240, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataMouseClicked
    //    int indexCustomer = -1, indexKendaraan = -1;
        action = "baharui";
        
        tambahDataButton.setEnabled(false);
        cancelButton.setEnabled(true);
        saveButton.setEnabled(true);
        setPelangganEditDeleteButton(true);
        
        setComponentsPelanggan(false);
        
        int clickedRow = tableData.getSelectedRow();
        TableModel tableModel = tableData.getModel();
        
        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 0).toString());
        
        idPelangganField.setText(tableModel.getValueAt(clickedRow, 0).toString());
        namaPelangganField.setText(tableModel.getValueAt(clickedRow, 1).toString());
        nomorTeleponPelangganField.setText(tableModel.getValueAt(clickedRow, 2).toString());
        alamatPelangganArea.setText(tableModel.getValueAt(clickedRow, 3).toString());
        
        cancelButton.setEnabled(true);
    }//GEN-LAST:event_tableDataMouseClicked

    private void searchInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchInputKeyPressed

    }//GEN-LAST:event_searchInputKeyPressed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        showTableBySearch(searchInput.getText());
        
        clearText();
        setComponentsPelanggan(false);
        setPelangganEditDeleteButton(false);
        tambahDataButton.setEnabled(true);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void barukanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanButtonActionPerformed
        action = "baharui";
        setComponentsPelanggan(true);
        idPelangganField.setEnabled(false);
        setPelangganEditDeleteButton(true);
    }//GEN-LAST:event_barukanButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        action = "hapus";
        int dialog = JOptionPane.showConfirmDialog(rootPane, "yakin ingin melakukan " + action + "?");
        if( dialog == JOptionPane.CLOSED_OPTION || dialog == JOptionPane.NO_OPTION
                || dialog==JOptionPane.CANCEL_OPTION)
            return;
        
        pc.deletePelanggan(selectedId);
        
        clearText();
        setComponentsPelanggan(false);
        setPelangganEditDeleteButton(false);
        tambahDataButton.setEnabled(true);
        showTableBySearch("");
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void tambahDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahDataButtonActionPerformed
        action = "tambah";
        clearText();
        setComponentsPelanggan(true);
        idPelangganField.setEnabled(false);
    }//GEN-LAST:event_tambahDataButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            inputKosongPelangganException();
            
            double telepon = Double.parseDouble(nomorTeleponPelangganField.getText());
            
            int opsi = JOptionPane.showConfirmDialog(rootPane, "Yakin ingin melakukan " +action+ "?");
            if(opsi == JOptionPane.NO_OPTION || opsi == JOptionPane.CANCEL_OPTION || opsi == JOptionPane.CLOSED_OPTION){
                return;
            }
               
            if(action.equals("tambah")){
                Pelanggan pk = new Pelanggan(namaPelangganField.getText(), nomorTeleponPelangganField.getText(), 
                        alamatPelangganArea.getText());
                pc.insertDataPelanggan(pk);
            }else{
                Pelanggan pk = new Pelanggan(namaPelangganField.getText(), nomorTeleponPelangganField.getText(), 
                        alamatPelangganArea.getText());
                pc.updatePelanggan(pk, selectedId);
                selectedId = -1;
            }
            
            clearText();
            setComponentsPelanggan(false);
            setPelangganEditDeleteButton(false);
            tambahDataButton.setEnabled(true);
            showTableBySearch("");
        }catch (InputKosongException e) {
            JOptionPane.showMessageDialog(rootPane, e.message());
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "Telepon Harus Angka");
        }
                
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        clearText();
        setPelangganEditDeleteButton(false);
        setComponentsPelanggan(false);
        setPelangganEditDeleteButton(false);
        
        tambahDataButton.setEnabled(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void idPelangganFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPelangganFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPelangganFieldActionPerformed

    private void nomorTeleponPelangganFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomorTeleponPelangganFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomorTeleponPelangganFieldActionPerformed

    private void nomorTeleponPelangganFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomorTeleponPelangganFieldKeyTyped
  
    }//GEN-LAST:event_nomorTeleponPelangganFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApotekLabel;
    private javax.swing.JLabel KaryawanApotekLabel;
    private javax.swing.JTextArea alamatPelangganArea;
    private javax.swing.JLabel alamatPelangganLabel;
    private javax.swing.JPanel alamatPelangganPanel;
    private javax.swing.JScrollPane alamatPelangganScrollPanel;
    private javax.swing.JButton barukanButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel dataFormPanel;
    private javax.swing.JButton hapusButton;
    private javax.swing.JTextField idPelangganField;
    private javax.swing.JLabel idPelangganLabel;
    private javax.swing.JPanel idPelangganPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField namaPelangganField;
    private javax.swing.JLabel namaPelangganLabel;
    private javax.swing.JPanel namaPelangganPanel;
    private javax.swing.JLabel nomorTeleponLabelPelanggan;
    private javax.swing.JTextField nomorTeleponPelangganField;
    private javax.swing.JPanel nomorTeleponPelangganPanel;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchInput;
    private javax.swing.JPanel searchInputPanel;
    private javax.swing.JTable tableData;
    private javax.swing.JButton tambahDataButton;
    // End of variables declaration//GEN-END:variables
}
