/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelView;

/**
 *
 * @author vina qhurotu aini
 */
import control.SupplierControl;
import control.ApotekerControl;
import control.PengadaanObatControl;
import control.ObatControl;

import exception.*;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import java.awt.Component;
import javax.swing.DefaultComboBoxModel;

import model.Apoteker;
import model.Supplier;
import model.Obat;
import model.PengadaanObat;

import table.TablePengadaanObat;

public class PengadaanObatPanel extends javax.swing.JPanel {

    private PengadaanObatControl pengadaanObatControl;
    private SupplierControl supplierControl;
    private ApotekerControl apotekerControl;
    private ObatControl obatControl;
    
    private PengadaanObatControl po = null;
    String action = null;
    int selectedId = 0; 
    
    List<Supplier> listSupplier;
    List<Apoteker> listApoteker;
    List<Obat> listObat;
    
    private Component rootPane;
    
    public void setApotekerToDropDown(){
        listApoteker = apotekerControl.showListApoteker();
        System.out.println(listApoteker.size());
        for(int i = 0; i < listApoteker.size(); i++){
            apotekerjComboBox2.addItem(listApoteker.get(i));
        }
    }
    
    public void setSupplierToDropDown(){
        listSupplier = supplierControl.showListSupplier();
        System.out.println(listSupplier.size());
        for(int i = 0; i < listSupplier.size(); i++){
            supplierjComboBox3.addItem(listSupplier.get(i));
        }
    }
    
    public void setObatToDropDown(){
        listObat = obatControl.showListObat();
        System.out.println(listObat.size());
        for(int i = 0; i < listObat.size(); i++){
            obatjComboBox1.addItem(listObat.get(i));
        }
    }
    
    public void showTableBySearch(String target){
        tableData.setModel(pengadaanObatControl.showTable(target));
    }
    
    public void inputKosongException() throws InputKosongException{
       if(supplierjComboBox3.getSelectedIndex() == -1 || apotekerjComboBox2.getSelectedIndex() == -1 || obatjComboBox1.getSelectedIndex() == -1 
               || jumlahObatField.getText().isEmpty() || tanggaljTextField1.getText().isEmpty()){ 
               throw new InputKosongException();
       }
    }
    
    public void clearText(){
        supplierjComboBox3.setSelectedIndex(-1);
        apotekerjComboBox2.setSelectedIndex(-1);
        obatjComboBox1.setSelectedIndex(-1);
        
        jumlahObatField.setText("");
        tanggaljTextField1.setText("");
        idPengadaanField.setText("");
        hargajTextArea1.setText("Rp ");
    }
    
    public void setEdiDeleteButton(boolean value){
        barukanButton.setEnabled(value);
        hapusButton.setEnabled(value);
    }
    
    public void setComponent(boolean value){
        supplierjComboBox3.setEnabled(value);
        apotekerjComboBox2.setEnabled(value);
        obatjComboBox1.setEnabled(value);
        
        jumlahObatField.setEnabled(value);
        tanggaljTextField1.setEnabled(value);
        hargajTextArea1.setEnabled(false);
        idPengadaanField.setEnabled(false);
        
        saveButton.setEnabled(value);
        cancelButton.setEnabled(value);
    }
    
    public PengadaanObatPanel() {
        initComponents();
        setOpaque(false);
        
        supplierControl = new SupplierControl();
        apotekerControl = new ApotekerControl();
        obatControl = new ObatControl();
        pengadaanObatControl = new PengadaanObatControl();
        
        setSupplierToDropDown();
        setApotekerToDropDown();
        setObatToDropDown();
        
        showTableBySearch("");
        
        clearText();
        setComponent(false);
        setEdiDeleteButton(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ApotekLabel = new javax.swing.JLabel();
        KaryawanApotekLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        searchInputPanel = new javax.swing.JPanel();
        searchInput = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        buttonPanel = new javax.swing.JPanel();
        barukanButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        tambahDataButton = new javax.swing.JButton();
        dataFormPanel = new javax.swing.JPanel();
        gajiApotekerPanel = new javax.swing.JPanel();
        jumlahObatLabel = new javax.swing.JLabel();
        jumlahObatField = new javax.swing.JTextField();
        PengalamanKerjaPanel = new javax.swing.JPanel();
        namaObatLabel = new javax.swing.JLabel();
        obatjComboBox1 = new javax.swing.JComboBox<>();
        idPelangganPanel = new javax.swing.JPanel();
        idPengadaanLabel = new javax.swing.JLabel();
        idPengadaanField = new javax.swing.JTextField();
        namaPelangganPanel = new javax.swing.JPanel();
        namaSupplierLabel = new javax.swing.JLabel();
        supplierjComboBox3 = new javax.swing.JComboBox<>();
        nomorTeleponPelangganPanel = new javax.swing.JPanel();
        namaApoteker = new javax.swing.JLabel();
        apotekerjComboBox2 = new javax.swing.JComboBox<>();
        idPelangganPanel3 = new javax.swing.JPanel();
        hargaLabel3 = new javax.swing.JLabel();
        hargajTextArea1 = new javax.swing.JTextArea();
        tanggaljTextField1 = new javax.swing.JTextField();
        tanggalLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1240, 704));

        jPanel1.setBackground(new java.awt.Color(218, 168, 168));
        jPanel1.setPreferredSize(new java.awt.Dimension(1210, 706));

        ApotekLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        ApotekLabel.setForeground(new java.awt.Color(0, 0, 0));
        ApotekLabel.setText("Pengadaan Obat");

        KaryawanApotekLabel.setFont(new java.awt.Font("Bahnschrift", 0, 10)); // NOI18N
        KaryawanApotekLabel.setForeground(new java.awt.Color(109, 96, 96));
        KaryawanApotekLabel.setText("Penyediaan Obat");

        mainPanel.setBackground(new java.awt.Color(238, 230, 230));

        searchInputPanel.setBackground(new java.awt.Color(238, 230, 230));

        searchInput.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchInputKeyPressed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(27, 26, 85));
        searchButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Cari");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchInputPanelLayout = new javax.swing.GroupLayout(searchInputPanel);
        searchInputPanel.setLayout(searchInputPanelLayout);
        searchInputPanelLayout.setHorizontalGroup(
            searchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchInputPanelLayout.createSequentialGroup()
                .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchInputPanelLayout.setVerticalGroup(
            searchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchInput)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cancelButton.setBackground(new java.awt.Color(237, 8, 0));
        cancelButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Batalkan");
        cancelButton.setPreferredSize(new java.awt.Dimension(72, 21));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(51, 178, 73));
        saveButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Simpan");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableData);

        buttonPanel.setBackground(new java.awt.Color(238, 230, 230));

        barukanButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanButton.setText("Barukan");
        barukanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanButtonActionPerformed(evt);
            }
        });

        hapusButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        tambahDataButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahDataButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahDataButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahDataButton.setText("Tambah");
        tambahDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahDataButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahDataButton)
                .addGap(18, 18, 18)
                .addComponent(barukanButton)
                .addGap(18, 18, 18)
                .addComponent(hapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(tambahDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dataFormPanel.setBackground(new java.awt.Color(238, 230, 230));

        gajiApotekerPanel.setBackground(new java.awt.Color(238, 230, 230));

        jumlahObatLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jumlahObatLabel.setForeground(new java.awt.Color(0, 0, 0));
        jumlahObatLabel.setText("Jumlah Obat");

        jumlahObatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahObatFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gajiApotekerPanelLayout = new javax.swing.GroupLayout(gajiApotekerPanel);
        gajiApotekerPanel.setLayout(gajiApotekerPanelLayout);
        gajiApotekerPanelLayout.setHorizontalGroup(
            gajiApotekerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gajiApotekerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gajiApotekerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jumlahObatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addComponent(jumlahObatField))
                .addContainerGap())
        );
        gajiApotekerPanelLayout.setVerticalGroup(
            gajiApotekerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gajiApotekerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jumlahObatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jumlahObatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PengalamanKerjaPanel.setBackground(new java.awt.Color(238, 230, 230));

        namaObatLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        namaObatLabel.setForeground(new java.awt.Color(0, 0, 0));
        namaObatLabel.setText("Nama Obat");

        javax.swing.GroupLayout PengalamanKerjaPanelLayout = new javax.swing.GroupLayout(PengalamanKerjaPanel);
        PengalamanKerjaPanel.setLayout(PengalamanKerjaPanelLayout);
        PengalamanKerjaPanelLayout.setHorizontalGroup(
            PengalamanKerjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PengalamanKerjaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PengalamanKerjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaObatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(obatjComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PengalamanKerjaPanelLayout.setVerticalGroup(
            PengalamanKerjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PengalamanKerjaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaObatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(obatjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        idPelangganPanel.setBackground(new java.awt.Color(238, 230, 230));

        idPengadaanLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        idPengadaanLabel.setForeground(new java.awt.Color(0, 0, 0));
        idPengadaanLabel.setText("ID Pengadaan");

        idPengadaanField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPengadaanFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout idPelangganPanelLayout = new javax.swing.GroupLayout(idPelangganPanel);
        idPelangganPanel.setLayout(idPelangganPanelLayout);
        idPelangganPanelLayout.setHorizontalGroup(
            idPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idPengadaanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idPengadaanField))
                .addContainerGap())
        );
        idPelangganPanelLayout.setVerticalGroup(
            idPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idPengadaanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idPengadaanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        namaPelangganPanel.setBackground(new java.awt.Color(238, 230, 230));

        namaSupplierLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        namaSupplierLabel.setForeground(new java.awt.Color(0, 0, 0));
        namaSupplierLabel.setText("Nama Supplier");

        supplierjComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierjComboBox3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout namaPelangganPanelLayout = new javax.swing.GroupLayout(namaPelangganPanel);
        namaPelangganPanel.setLayout(namaPelangganPanelLayout);
        namaPelangganPanelLayout.setHorizontalGroup(
            namaPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaSupplierLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(supplierjComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        namaPelangganPanelLayout.setVerticalGroup(
            namaPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaSupplierLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(supplierjComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        nomorTeleponPelangganPanel.setBackground(new java.awt.Color(238, 230, 230));

        namaApoteker.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        namaApoteker.setForeground(new java.awt.Color(0, 0, 0));
        namaApoteker.setText("Nama Apoteker");

        javax.swing.GroupLayout nomorTeleponPelangganPanelLayout = new javax.swing.GroupLayout(nomorTeleponPelangganPanel);
        nomorTeleponPelangganPanel.setLayout(nomorTeleponPelangganPanelLayout);
        nomorTeleponPelangganPanelLayout.setHorizontalGroup(
            nomorTeleponPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomorTeleponPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nomorTeleponPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaApoteker, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(apotekerjComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        nomorTeleponPelangganPanelLayout.setVerticalGroup(
            nomorTeleponPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomorTeleponPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaApoteker)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(apotekerjComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        idPelangganPanel3.setBackground(new java.awt.Color(238, 230, 230));

        hargaLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        hargaLabel3.setForeground(new java.awt.Color(0, 0, 0));
        hargaLabel3.setText("Harga Total");

        hargajTextArea1.setColumns(20);
        hargajTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        hargajTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        hargajTextArea1.setRows(5);
        hargajTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hargajTextArea1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout idPelangganPanel3Layout = new javax.swing.GroupLayout(idPelangganPanel3);
        idPelangganPanel3.setLayout(idPelangganPanel3Layout);
        idPelangganPanel3Layout.setHorizontalGroup(
            idPelangganPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPelangganPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idPelangganPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hargaLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, idPelangganPanel3Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(hargajTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        idPelangganPanel3Layout.setVerticalGroup(
            idPelangganPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPelangganPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hargaLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hargajTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tanggaljTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggaljTextField1ActionPerformed(evt);
            }
        });

        tanggalLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        tanggalLabel1.setForeground(new java.awt.Color(0, 0, 0));
        tanggalLabel1.setText("Tanggal Pengadaan");

        javax.swing.GroupLayout dataFormPanelLayout = new javax.swing.GroupLayout(dataFormPanel);
        dataFormPanel.setLayout(dataFormPanelLayout);
        dataFormPanelLayout.setHorizontalGroup(
            dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataFormPanelLayout.createSequentialGroup()
                        .addGroup(dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idPelangganPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(namaPelangganPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PengalamanKerjaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gajiApotekerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(dataFormPanelLayout.createSequentialGroup()
                        .addComponent(nomorTeleponPelangganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tanggaljTextField1)
                            .addGroup(dataFormPanelLayout.createSequentialGroup()
                                .addComponent(tanggalLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addComponent(idPelangganPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        dataFormPanelLayout.setVerticalGroup(
            dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataFormPanelLayout.createSequentialGroup()
                        .addGroup(dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idPelangganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PengalamanKerjaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaPelangganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gajiApotekerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomorTeleponPelangganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataFormPanelLayout.createSequentialGroup()
                                .addComponent(tanggalLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tanggaljTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(idPelangganPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(searchInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(ApotekLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KaryawanApotekLabel)
                .addContainerGap(1040, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(41, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApotekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KaryawanApotekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(674, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(18, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1240, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataMouseClicked
        int indexSupplier = -1, indexApoteker = -1, indexObat = -1;
        action = "baharui";
        
        tambahDataButton.setEnabled(false);
        cancelButton.setEnabled(true);
        saveButton.setEnabled(true);
        setEdiDeleteButton(true);
        
        setComponent(false);
        
        int clickedRow = tableData.getSelectedRow();
        TableModel tableModel = tableData.getModel();
        
        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 9).toString());
        
        idPengadaanField.setText(tableModel.getValueAt(clickedRow, 9).toString());
        jumlahObatField.setText(tableModel.getValueAt(clickedRow, 4).toString());
        tanggaljTextField1.setText(tableModel.getValueAt(clickedRow, 3).toString());
        hargajTextArea1.setText("Rp " +tableModel.getValueAt(clickedRow, 5).toString());
        
        for(Supplier supplier : listSupplier){
            if(supplier.getId_supplier() == Integer.parseInt(tableModel.getValueAt(clickedRow, 7).toString())){
                indexSupplier = listSupplier.indexOf(supplier);
            }
        }
        
        for(Apoteker apoteker : listApoteker){
            if(apoteker.getId_apoteker() == Integer.parseInt(tableModel.getValueAt(clickedRow, 8).toString())){
                indexApoteker = listApoteker.indexOf(apoteker);
            }
        }
        
        for(Obat obat : listObat){
            if(obat.getId_obat()== Integer.parseInt(tableModel.getValueAt(clickedRow, 6).toString())){
                indexObat = listObat.indexOf(obat);
            }
        }
        
        supplierjComboBox3.setSelectedIndex(indexSupplier);
        apotekerjComboBox2.setSelectedIndex(indexApoteker);
        obatjComboBox1.setSelectedIndex(indexObat);
        cancelButton.setEnabled(true);
    }//GEN-LAST:event_tableDataMouseClicked

    private void searchInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchInputKeyPressed

    }//GEN-LAST:event_searchInputKeyPressed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        showTableBySearch(searchInput.getText());
        
        clearText();
        setComponent(false);
        setEdiDeleteButton(false);
        tambahDataButton.setEnabled(true);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void barukanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanButtonActionPerformed
        action = "baharui";
        setComponent(true);
        tanggaljTextField1.setEnabled(false);
        setEdiDeleteButton(true);
    }//GEN-LAST:event_barukanButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        action = "hapus";
        
        int opsi = JOptionPane.showConfirmDialog(rootPane, "Yakin ingin melakukan "+action+ "?");
        if(opsi == JOptionPane.NO_OPTION || opsi == JOptionPane.CANCEL_OPTION || opsi == JOptionPane.CLOSED_OPTION){
               return;
        }
        
        pengadaanObatControl.deletePengadaan(selectedId);
        
        clearText();
        setComponent(false);
        setEdiDeleteButton(false);
        tambahDataButton.setEnabled(true);
        showTableBySearch("");
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void tambahDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahDataButtonActionPerformed
        action = "tambah";
        clearText();
        setComponent(true);
    }//GEN-LAST:event_tambahDataButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try{
            inputKosongException();
            
            String tanggal = "";
            int kuantitas = 0;
            
            int selectedIndexSupplier = supplierjComboBox3.getSelectedIndex();
            Supplier selectedSupplier = listSupplier.get(selectedIndexSupplier);
            
            int selectedIndexApoteker = apotekerjComboBox2.getSelectedIndex();
            Apoteker selectedApoteker = listApoteker.get(selectedIndexApoteker);
            
            int selectedIndexObat = obatjComboBox1.getSelectedIndex();
            Obat selectedObat = listObat.get(selectedIndexObat);
            
            double totalHarga = Integer.parseInt(jumlahObatField.getText()) * selectedObat.getHarga_obat();
            tanggal = tanggaljTextField1.getText();
            kuantitas = Integer.parseInt(jumlahObatField.getText());
            
            int opsi = JOptionPane.showConfirmDialog(rootPane, "Yakin ingin melakukan " +action+ "?");
            if(opsi == JOptionPane.NO_OPTION || opsi == JOptionPane.CANCEL_OPTION || opsi == JOptionPane.CLOSED_OPTION){
                return;
            }

            if(action.equals("tambah")){
                PengadaanObat po = new PengadaanObat(selectedApoteker.getId_apoteker(), selectedSupplier.getId_supplier(), selectedObat.getId_obat(), selectedApoteker, selectedSupplier, selectedObat, totalHarga, tanggal, kuantitas);
                pengadaanObatControl.insertDataPengadaan(po);
            }else{
                PengadaanObat po = new PengadaanObat(selectedApoteker.getId_apoteker(), selectedSupplier.getId_supplier(), selectedObat.getId_obat(), selectedApoteker, selectedSupplier, selectedObat, totalHarga, tanggal, kuantitas);
                pengadaanObatControl.updatePengadaan(po, selectedId);
                selectedId = -1;
            }
            clearText();
            setComponent(false);
            setEdiDeleteButton(false);
            tableData.setEnabled(true);
            showTableBySearch("");
        }catch(InputKosongException e){
            JOptionPane.showMessageDialog(rootPane, e.message());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "Kuantitas Harus Berupa Angka");
        }
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        clearText();
        setEdiDeleteButton(false);
        setComponent(false);
        setEdiDeleteButton(false);
        
        tambahDataButton.setEnabled(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void jumlahObatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahObatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahObatFieldActionPerformed

    private void idPengadaanFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPengadaanFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPengadaanFieldActionPerformed

    private void tanggaljTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggaljTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggaljTextField1ActionPerformed

    private void supplierjComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierjComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierjComboBox3ActionPerformed

    private void hargajTextArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hargajTextArea1MouseClicked
        try{
            inputKosongException();
            
            int selectedIndexObat = obatjComboBox1.getSelectedIndex();
            Obat selectedObat = listObat.get(selectedIndexObat);
            
            double totalHarga = Integer.parseInt(jumlahObatField.getText()) * selectedObat.getHarga_obat();
            
            hargajTextArea1.setText("Rp " +Double.toString(totalHarga));
        }catch(InputKosongException e){
            JOptionPane.showMessageDialog(rootPane, e.message());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "Kuantitas Harus Berupa Angka");
        }
    }//GEN-LAST:event_hargajTextArea1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApotekLabel;
    private javax.swing.JLabel KaryawanApotekLabel;
    private javax.swing.JPanel PengalamanKerjaPanel;
    private javax.swing.JComboBox<Apoteker> apotekerjComboBox2;
    private javax.swing.JButton barukanButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel dataFormPanel;
    private javax.swing.JPanel gajiApotekerPanel;
    private javax.swing.JButton hapusButton;
    private javax.swing.JLabel hargaLabel3;
    private javax.swing.JTextArea hargajTextArea1;
    private javax.swing.JPanel idPelangganPanel;
    private javax.swing.JPanel idPelangganPanel3;
    private javax.swing.JTextField idPengadaanField;
    private javax.swing.JLabel idPengadaanLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlahObatField;
    private javax.swing.JLabel jumlahObatLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaApoteker;
    private javax.swing.JLabel namaObatLabel;
    private javax.swing.JPanel namaPelangganPanel;
    private javax.swing.JLabel namaSupplierLabel;
    private javax.swing.JPanel nomorTeleponPelangganPanel;
    private javax.swing.JComboBox<Obat> obatjComboBox1;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchInput;
    private javax.swing.JPanel searchInputPanel;
    private javax.swing.JComboBox<Supplier> supplierjComboBox3;
    private javax.swing.JTable tableData;
    private javax.swing.JButton tambahDataButton;
    private javax.swing.JLabel tanggalLabel1;
    private javax.swing.JTextField tanggaljTextField1;
    // End of variables declaration//GEN-END:variables
}
